### ISSUE TITLE
Custom filter sorting

### ISSUE THREAD

**Issue by famda** [hector-co/QueryX#3]
Hello,
Awesome library!

I'm using this library as my default filtering, sorting and paging library.
Wouldn't be nice to have Sorting on a property that is marked as a Custom filter?

Can you help?
Thanks in advance.

**Comment by hector-co** [comment]
Thank you for your feedback!

Custom filters are properties that are not necessarily mapped to the database, that's why they are excluded from filtering and sorting. For example I can add a custom filter called `OnlyHighPriority` and according to its value apply the corresponding filtering, I think I did not reflect that correctly in the examples.

Do you have an example to understand your scenario a little more?

**Comment by famda** [comment]
Hello,
Sorry for the late reply. :)

As an example, I have a model that maps a different name on a property like this:

![image](https://github.com/hector-co/QueryX/assets/26621392/9a7131f7-b011-4af9-b704-9a64249904b4)

This property is a string ("externally") and, on the DB, is a bool or a Enum.
When I create the query using the builder, I can have the value for the filtering but I don't have the value for the sorting:

![image](https://github.com/hector-co/QueryX/assets/26621392/ef83f716-dbc4-4192-beb1-93a2cc159ef3)

The create query method, ignores the value of the sorting on that field.
I'm not able to get the sorting for that specific property. 

My proposal would be to have that after the "CreateQuery" and then it's possible to apply it manually to the IQueryable.

What do you think?

**Comment by hector-co** [comment]
Hi, I think there could be a new method called `TryGetSortBy` which will receive the same parameter as `TryGetFilter` and will return a [SortValue](https://github.com/hector-co/QueryX/blob/main/src/QueryX/Filters/SortValue.cs) object as out parameter when success. I think that covers your requirement, doesn't it? I'll take a look at it these days

**Comment by famda** [comment]
Yes. That seems to be perfect!
Thanks a lot ;)
